"""
This type stub file was generated by pyright.
"""

import os as _os
import open3d as _open3d
from open3d.cuda.pybind.ml import *
from open3d.cpu.pybind.ml import *
from . import configs, datasets, utils, vis

if _open3d.__DEVICE_API__ == 'cuda':
    ...
else:
    ...
