"""
This type stub file was generated by pyright.
"""

import logging

class LogRecord(logging.LogRecord):
    """Class for logging information."""
    def getMessage(self): # -> str:
        ...
    


def get_runid(path): # -> str:
    """Get runid or an experiment."""
    ...

def code2md(code_text, language=...):
    """Format code as markdown for display (eg in tensorboard)"""
    ...

