"""
This type stub file was generated by pyright.
"""

import os
import sys
from . import geometry, io, visualization, utility, camera, core
import open3d.ml
from ctypes import CDLL as _CDLL
from ctypes.util import find_library as _find_library
from pathlib import Path as _Path
from open3d._build_config import _build_config

if _build_config["BUILD_GUI"] and not (_find_library('c++abi') or _find_library('c++')):
    ...
__DEVICE_API__ = ...
if _build_config["BUILD_CUDA_MODULE"]:
    ...
if __DEVICE_API__ == 'cpu':
    ...
__version__ = ...
if int(sys.version_info[0]) < 3:
    ...
if _build_config["BUILD_JUPYTER_EXTENSION"]:
    ...
if 'OPEN3D_ML_ROOT' in os.environ:
    ...
