"""
This type stub file was generated by pyright.
"""

class Colormap:
    """This class is used to create a color map for visualization of points."""
    class Point:
        """Initialize the class.

        Args:
            value: The scalar value index of the point.
            color: The color associated with the value.
        """
        def __init__(self, value, color) -> None:
            ...
        
        def __repr__(self): # -> str:
            """Represent the color and value in the colormap."""
            ...
        
    
    
    def __init__(self, points) -> None:
        ...
    
    def calc_u_array(self, values, range_min, range_max): # -> list[float]:
        """Generate the basic array based on the minimum and maximum range passed."""
        ...
    
    def calc_color_array(self, values, range_min, range_max): # -> list[list[float]]:
        """Generate the color array based on the minimum and maximum range passed.

        Args:
            values: The index of values.
            range_min: The minimum value in the range.
            range_max: The maximum value in the range.

        Returns:
            An array of color index based on the range passed.
        """
        ...
    
    @staticmethod
    def make_greyscale(): # -> Colormap:
        """Generate a greyscale colormap."""
        ...
    
    @staticmethod
    def make_rainbow(): # -> Colormap:
        """Generate the rainbow color array."""
        ...
    


