from typing import Optional
from . import core

def device_count() -> int: ...
def is_available() -> bool: ...
def release_cache() -> None: ...
def synchronize(device: Optional[core.Device] = None) -> None: ...
