"""
This type stub file was generated by pyright.
"""

import open3d
from open3d.ml.contrib import iou_3d_cpu as iou_3d, iou_3d_cuda as iou_3d, iou_bev_cpu as iou_bev, iou_bev_cuda as iou_bev
from .mAP import mAP, precision_3d

if open3d.core.cuda.device_count() > 0:
    ...
else:
    ...
