"""
This type stub file was generated by pyright.
"""

import open3d as _open3d
from open3d.cuda.pybind.ml.contrib import *
from open3d.cpu.pybind.ml.contrib import *

if _open3d.__DEVICE_API__ == 'cuda':
    ...
else:
    ...
